language: java
jdk:
  - oraclejdk11
deploy:
  provider: heroku
  api_key:
    secure: XB8ltWFFFiuwxtvvLkIcR30nPyGAjVh0p+9kR8nExn3myySAN+2QlagwH/s6mVt22Zn++Lp40Ig34VIBmEVIj1UypT8+2/7WuOMOeghDLwGiysv5MhenzJ856aUyHmTjFluWSVRXNlWudu5d/D0nS2N4Y+59LFzvA14yltQTL8zAu5qjwhAZur9TsJhlSf41i3uxB1P8jbXElxbyeY8wOEeeadsk0yCKh4VRGobTRRN0qqQBS8bVZv3kq0ymWHnqSIWBFOPauc4+SWmDA3XJXPt1Z3u2V30DS1u/r/8CyhU3HByZxUfzSVSEohEoL1zBJUsrIlNBR60UbYrJr9ThkA/x7vRC4Jufx9qH3JjnhC1J9t4HIiA7F8ka3BqyKNrEHDNFE49DkT0YHhL2zJADQnOURcpOc0DAuiHJTK3uqIbzVR7pyJ2vAP+MFb8eZakVke9oR66f65aqDEss7c7pDCdw/Jo44hTaRfnbUv5GNF7pQRlNiS11mnRjWhW3sJFElLIwefa+tSv73Q0mcDd+Twp06opO3XiCLkMe8B682RzGSwJPP3pNwNY2dJ85XeWyHAuYSPFac4YQz+AokRG9+fGiZbcCtm2tNQ2BuIJXRW5NmaELicTMZoEd+BTTjMB2X6fRpbRtOWVuTaaOy2qz0AefPfLMZijJ46Xdxz1tMf8=
  app: basic-spring